### ISSUE TITLE
Consider creating backups in the setup script

### ISSUE THREAD

**Issue by terranisu** [dhruvasagar/dotfiles#1]
Simple removal of the directories and dotfiles is not a nice approach:
https://github.com/dhruvasagar/dotfiles/blob/master/setup#L3-L14
I would be upset finding out all my dotfiles have been deleted.

It's better to check whether the directories and files exist and if they do, create backups of those before removal. Something like:
```bash
if [ -f ~/.vim ] ; then
  mv ~/.vim ~/.vim.bak
fi
```

**Comment by dhruvasagar** [comment]
All these are just symlinks to actual content within the dotfiles, you don't loose any data by deleting the symlinks, we just create them again further down in the setup script.

**Comment by dhruvasagar** [comment]
This was also done in an attempt to make this script idempotent, so that multiple calls would produce the same result.
