### ISSUE TITLE
no such hash table elements in dirsh

### ISSUE THREAD

**Issue by tracphil** [dhruvasagar/dotfiles#2]
Thanks for `dirsh`. I found it looking for an error I was getting with `direnv`.

In a directory, I have the following a `.zshrc` file:

```source
source $(pyenv prefix)/bin/aws_zsh_completer.sh
```

That part works great, however when I exit out of the directory to my home directory, I get this:

```source
dirsh: unloading
_dirsh_hook:unset:6: no such hash table element: _load
_dirsh_hook:unset:7: no such hash table element: _unload
```

Any ideas?

**Comment by dhruvasagar** [comment]
@tracphil Hi, Dirsh is designed to run these special functions `_load` and `_unload` when you enter and exit a directory respectively. The idea is you could place some initialization steps within `_load` and do some cleanup within `_unload`.

**Comment by tracphil** [comment]
Got it! Thanks again for your help!
